apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-buildbot
  annotations:
    volume.beta.kubernetes.io/storage-class: "sizable"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
